name: Sync To Gitee
on: [ push, delete, create ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/the-eric-kwok/my_userscripts.git"
          destination-repo: "git@gitee.com:erickwok404/my_userscripts.git"
